<?php
// autogenerated file 09.05.2012 12:52
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This is used to specify the type of Address of the Non Profit Charity 
 * organization. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AddressTypeCodeType.html
 *
 * @property string Contact
 * @property string Registered
 * @property string CustomCode
 */
class AddressTypeCodeType extends EbatNs_FacetType
{
	const CodeType_Contact = 'Contact';
	const CodeType_Registered = 'Registered';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AddressTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_AddressTypeCodeType = new AddressTypeCodeType();

?>
