<?php
// autogenerated file 15.11.2010 08:32
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the LocalMarketRegularSubscription feature. If this fieldis present, the 
 * corresponding feature applies to the category. Thefield is returned as an empty 
 * element (i.e., a boolean value is notreturned). A subscription for Local Market 
 * for Vehicles will bereturned by GetUser if a dealer has subscribed to any of the 
 * followingLocal Market Regular sub-types: Vehicles Regular Six Months,Vehicles 
 * Regular Special Promotion, Vehicles Regular MultistoreLevel S, Vehicles Regular 
 * Multistore Level M, or Vehicles RegularMultistore Level L. Each of these 
 * sub-types has a separate discountand billing cycle. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LocalMarketRegularSubscriptionDefinitionType.html
 *
 */
class LocalMarketRegularSubscriptionDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LocalMarketRegularSubscriptionDefinitionType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}
	}
}
?>
