<?php
// autogenerated file 10.09.2012 12:33
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';

/**
 * This type specifies the shipping service and cost of the domestic or 
 * international leg of a Global Exchange shipment. If its fields are returned as 
 * part of a 
 * <strong>SellerShipmentToLogisticsProvider.ShippingServiceDetails</strong> 
 * container, the information applies to the domestic leg of the shipment. If its 
 * fields are returned as part of a 
 * <strong>LogisticsProviderShipmentToBuyer.ShippingServiceDetails</strong> 
 * container, the information applies to the international leg of the 
 * shipment.<br/><br/><span class="tablenote"><strong>Note:</strong> The Global 
 * Exchange program is available for testing with simulated responses in the 
 * Sandbox in mid-June 2012. The full functionality of the Global Exchange program 
 * will be available in August 2012.</span> 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MultiLegShippingServiceType.html
 *
 */
class MultiLegShippingServiceType extends EbatNs_ComplexType
{
	/**
	 * @var token
	 */
	protected $ShippingService;
	/**
	 * @var AmountType
	 */
	protected $TotalShippingCost;

	/**
	 * @return token
	 */
	function getShippingService()
	{
		return $this->ShippingService;
	}
	/**
	 * @return void
	 * @param token $value 
	 */
	function setShippingService($value)
	{
		$this->ShippingService = $value;
	}
	/**
	 * @return AmountType
	 */
	function getTotalShippingCost()
	{
		return $this->TotalShippingCost;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setTotalShippingCost($value)
	{
		$this->TotalShippingCost = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MultiLegShippingServiceType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'ShippingService' =>
					array(
						'required' => false,
						'type' => 'token',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'TotalShippingCost' =>
					array(
						'required' => false,
						'type' => 'AmountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
