<?php
// autogenerated file 09.05.2012 13:11
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the payment options group feature. If a field of this type is present, 
 * the corresponding feature applies to the site. The field is returned as an 
 * integer. The below are the integer values returned and its meanings.0 - Ebay 
 * Payment Process Enabled1 - Non Standard Payments Enabled2 - Ebay Payment Process 
 * Excluded 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PaymentOptionsGroupEnabledDefinitionType.html
 *
 */
class PaymentOptionsGroupEnabledDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PaymentOptionsGroupEnabledDefinitionType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}
	}
}
?>
