<?php
// autogenerated file 09.05.2012 13:08
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * The payment type 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PayoutMethodType.html
 *
 * @property string PAYPAL
 * @property string EFT
 * @property string MONEYBOOKERS
 */
class PayoutMethodType extends EbatNs_FacetType
{
	const CodeType_PAYPAL = 'PAYPAL';
	const CodeType_EFT = 'EFT';
	const CodeType_MONEYBOOKERS = 'MONEYBOOKERS';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PayoutMethodType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PayoutMethodType = new PayoutMethodType();

?>
