<?php
// autogenerated file 10.09.2012 12:30
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * The PaymentProfileCategoryGroup, ReturnPolicyProfileCategoryGroup, and 
 * ShippingProfileCategoryGroup fields are returned in the GetCategoryFeature 
 * response if the corresponding Business Policies profile types apply to the 
 * category. The field is returned as an emptyelement. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ProfileCategoryGroupDefinitionType.html
 *
 */
class ProfileCategoryGroupDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ProfileCategoryGroupDefinitionType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}
	}
}
?>
