<?php
// autogenerated file 09.05.2012 13:15
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * A code indicating the reason why a refund was not issued by the seller. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RefundFailureCodeType.html
 *
 * @property string NoPayoutMethodOnFile
 * @property string PaypalBillingAgreementCanceled
 * @property string AllFundingSourcesUnuseable
 * @property string WouldExceedSpendingLimit
 * @property string UserRestricted
 * @property string RemedyError
 * @property string PaypalBAIsNotAvailable
 * @property string eBayUserAgreementNotAvailable
 * @property string PaypalRiskDeclinesTransaction
 * @property string CustomCode
 */
class RefundFailureCodeType extends EbatNs_FacetType
{
	const CodeType_NoPayoutMethodOnFile = 'NoPayoutMethodOnFile';
	const CodeType_PaypalBillingAgreementCanceled = 'PaypalBillingAgreementCanceled';
	const CodeType_AllFundingSourcesUnuseable = 'AllFundingSourcesUnuseable';
	const CodeType_WouldExceedSpendingLimit = 'WouldExceedSpendingLimit';
	const CodeType_UserRestricted = 'UserRestricted';
	const CodeType_RemedyError = 'RemedyError';
	const CodeType_PaypalBAIsNotAvailable = 'PaypalBAIsNotAvailable';
	const CodeType_eBayUserAgreementNotAvailable = 'eBayUserAgreementNotAvailable';
	const CodeType_PaypalRiskDeclinesTransaction = 'PaypalRiskDeclinesTransaction';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RefundFailureCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundFailureCodeType = new RefundFailureCodeType();

?>
