<?php
// autogenerated file 22.07.2011 08:57
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Reserved for future use. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RequiredSellerActionCodeType.html
 *
 * @property string ResolveCase
 * @property string PostShippingInfo
 * @property string None
 * @property string CustomCode
 */
class RequiredSellerActionCodeType extends EbatNs_FacetType
{
	const CodeType_ResolveCase = 'ResolveCase';
	const CodeType_PostShippingInfo = 'PostShippingInfo';
	const CodeType_None = 'None';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RequiredSellerActionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RequiredSellerActionCodeType = new RequiredSellerActionCodeType();

?>
