<?php
// autogenerated file 24.02.2011 11:33
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * (out) Returned after a call to SetNotificationPreferences to indicate that the 
 * call succeeded. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetNotificationPreferencesResponseType.html
 *
 */
class SetNotificationPreferencesResponseType extends AbstractResponseType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetNotificationPreferencesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}
	}
}
?>
